language: bash
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

job:
  include:
    - stage: Build
      script: ./scripts/build.sh
    - stage: Check
      script: ./scripts/check.sh
    - stage: Deploy
      script: ./scripts/deploy.sh