language: bash
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: Build
      script: ./scripts/build.sh
    - stage: Check
      script: ./scripts/check.sh
    - stage: Deploy
      deploy:
        - provider: script
          script: ./scripts/deploy.sh
          skip_cleanup: true
          on:
            tags: true